# Generated by Django 3.1.2 on 2020-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('position',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
